#!/bin/bash
# SoftRoCE persistence for WSL2 / Ubuntu
# Creates rxe links on boot and verifies they're ACTIVE
# Usage: sudo ./softroce_persist.sh install  # install as systemd service
#        sudo ./softroce_persist.sh create   # create links now
#        ./softroce_persist.sh status        # show status

set -euo pipefail

SERVICE_NAME="vulkanvm-softroce"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"
SCRIPT_FILE="/usr/local/bin/vulkanvm-softroce-create"
LOGFILE="/var/log/vulkanvm-softroce.log"

# Interfaces to create rxe links on (adjust for your setup)
INTERFACES=("eth0" "lo")

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOGFILE"
}

create_links() {
    log "Creating SoftRoCE links on interfaces: ${INTERFACES[*]}"
    
    for iface in "${INTERFACES[@]}"; do
        # Check if interface exists
        if ! ip link show "$iface" >/dev/null 2>&1; then
            log "Interface $iface does not exist, skipping"
            continue
        fi
        
        # Generate link name (rxe0, rxe1, etc.)
        local idx=0
        for existing in /sys/class/infiniband/rxe*/netdev; do
            if [[ -e "$existing" ]] && [[ "$(cat "$existing")" == "$iface" ]]; then
                log "Interface $iface already has an rxe link"
                continue 2
            fi
        done
        
        # Find next available rxe index
        for i in {0..15}; do
            if [[ ! -e "/sys/class/infiniband/rxe$i" ]]; then
                idx=$i
                break
            fi
        done
        
        local link_name="rxe$idx"
        
        # Create the link
        if rdma link add "$link_name" type rxe netdev "$iface" 2>/dev/null; then
            log "Created $link_name on $iface"
        else
            log "Failed to create $link_name on $iface (may already exist)"
        fi
    done
    
    # Wait for links to become ACTIVE
    log "Waiting for links to become ACTIVE..."
    for i in {1..10}; do
        local active_count=0
        local total_count=0
        for link in /sys/class/infiniband/rxe*/state; do
            if [[ -e "$link" ]]; then
                total_count=$((total_count + 1))
                if [[ "$(cat "$link")" == "ACTIVE" ]]; then
                    active_count=$((active_count + 1))
                fi
            fi
        done
        
        if [[ $total_count -gt 0 && $active_count -eq $total_count ]]; then
            log "All $total_count SoftRoCE links are ACTIVE"
            break
        fi
        
        sleep 1
    done
    
    # Show final status
    show_status
}

show_status() {
    echo "=== SoftRoCE Status ==="
    echo "ibv_devices:"
    ibv_devices 2>/dev/null || echo "  (ibv_devices not found)"
    echo ""
    echo "rdma link show:"
    rdma link show 2>/dev/null || echo "  (rdma link not found)"
    echo ""
    echo "Kernel module:"
    lsmod | grep -E "(rdma_rxe|ib_core|ib_uverbs)" || echo "  (no RDMA modules loaded)"
    echo ""
    echo "Interfaces:"
    for iface in "${INTERFACES[@]}"; do
        if ip link show "$iface" >/dev/null 2>&1; then
            echo "  $iface: UP"
        else
            echo "  $iface: NOT FOUND"
        fi
    done
}

install_service() {
    log "Installing systemd service..."
    
    # Create the creation script
    cat > "$SCRIPT_FILE" << 'EOF'
#!/bin/bash
# Auto-generated by vulkanvm-softroce persistence installer
set -euo pipefail
INTERFACES=("eth0" "lo")
LOGFILE="/var/log/vulkanvm-softroce.log"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" >> "$LOGFILE"
}

for iface in "${INTERFACES[@]}"; do
    if ! ip link show "$iface" >/dev/null 2>&1; then
        continue
    fi
    
    # Check if already linked
    already_linked=false
    for existing in /sys/class/infiniband/rxe*/netdev; do
        if [[ -e "$existing" ]] && [[ "$(cat "$existing")" == "$iface" ]]; then
            already_linked=true
            break
        fi
    done
    
    if [[ "$already_linked" == "true" ]]; then
        continue
    fi
    
    # Find next available index
    for i in {0..15}; do
        if [[ ! -e "/sys/class/infiniband/rxe$i" ]]; then
            rdma link add "rxe$i" type rxe netdev "$iface" 2>>"$LOGFILE"
            log "Created rxe$i on $iface"
            break
        fi
    done
done

# Wait for ACTIVE
for i in {1..10}; do
    active=0
    total=0
    for link in /sys/class/infiniband/rxe*/state; do
        if [[ -e "$link" ]]; then
            total=$((total + 1))
            if [[ "$(cat "$link")" == "ACTIVE" ]]; then
                active=$((active + 1))
            fi
        fi
    done
    if [[ $total -gt 0 && $active -eq $total ]]; then
        log "All $total SoftRoCE links ACTIVE"
        break
    fi
    sleep 1
done
EOF
    chmod +x "$SCRIPT_FILE"
    
    # Create systemd service
    cat > "$SERVICE_FILE" << EOF
[Unit]
Description=VulkanVM SoftRoCE (rxe) Link Creation
Documentation=https://github.com/XxChonkExX/Vulkan-Automaton-VM
After=network-online.target
Wants=network-online.target
DefaultDependencies=no

[Service]
Type=oneshot
ExecStart=$SCRIPT_FILE
RemainAfterExit=yes
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF
    
    systemctl daemon-reload
    systemctl enable "$SERVICE_NAME"
    log "Service installed and enabled. Start with: systemctl start $SERVICE_NAME"
}

uninstall_service() {
    log "Uninstalling systemd service..."
    systemctl disable "$SERVICE_NAME" 2>/dev/null || true
    systemctl stop "$SERVICE_NAME" 2>/dev/null || true
    rm -f "$SERVICE_FILE" "$SCRIPT_FILE"
    systemctl daemon-reload
    log "Service uninstalled"
}

case "${1:-status}" in
    install)
        install_service
        ;;
    uninstall)
        uninstall_service
        ;;
    create)
        create_links
        ;;
    status)
        show_status
        ;;
    logs)
        journalctl -u "$SERVICE_NAME" -f
        ;;
    *)
        echo "Usage: $0 {install|uninstall|create|status|logs}"
        exit 1
        ;;
esac